package com.lifeenrichment.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Stores per-user notification channel preferences for each notification type.
 *
 * <p>One row per (user, notificationType) pair. Defaults: email on, SMS off, push off.
 * The service layer falls back to email-only when no preference record exists.
 *
 * <p>The unique constraint {@code uq_notification_preference_user_type} enforces that each
 * user may have at most one preference record per {@link NotificationType}. An index on
 * {@code user_id} supports efficient lookups of all preferences for a given user.
 *
 * <p>Preference records are created lazily — a missing row means "use defaults", not an error.
 * The {@code NotificationService} calls
 * {@code NotificationPreferenceRepository#findByUserIdAndNotificationType} before dispatching
 * and falls back to email-only when no record is found.
 *
 * @see NotificationLog
 * @see NotificationType
 */
@Entity
@Table(name = "notification_preferences",
       uniqueConstraints = @UniqueConstraint(
               name = "uq_notification_preference_user_type",
               columnNames = {"user_id", "notification_type"}
       ),
       indexes = {
           @Index(name = "idx_notif_pref_user", columnList = "user_id")
       })
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class NotificationPreference {

    /** Surrogate primary key; UUID generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The user whose channel preferences this record describes.
     * Loaded lazily to avoid unnecessary joins when only preference flags are needed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The notification event type this preference applies to.
     * Together with {@link #user}, forms the unique key for this record.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "notification_type", nullable = false)
    private NotificationType notificationType;

    /**
     * Whether the user wishes to receive this notification type by email.
     * Defaults to {@code true} — email is the primary delivery channel for most users.
     */
    @Builder.Default
    @Column(name = "email_enabled", nullable = false)
    private boolean emailEnabled = true;

    /**
     * Whether the user wishes to receive this notification type by SMS.
     * Defaults to {@code false}; must be explicitly opted in and requires a verified phone number.
     */
    @Builder.Default
    @Column(name = "sms_enabled", nullable = false)
    private boolean smsEnabled = false;

    /**
     * Whether the user wishes to receive this notification type as a push notification.
     * Defaults to {@code false}; requires the user to have a registered device token (FCM).
     */
    @Builder.Default
    @Column(name = "push_enabled", nullable = false)
    private boolean pushEnabled = false;

    /** Timestamp set automatically when the preference record is first persisted. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp updated automatically whenever the preference record is modified. */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Enumeration of all notification event types recognised by the system.
     *
     * <p>Used as the discriminator in {@link NotificationPreference} (one preference row per
     * user per type) and as the event label in {@link NotificationLog} dispatch records.
     * New event types should also be reflected in the Thymeleaf email templates under
     * {@code resources/templates/notification/}.
     */
    public enum NotificationType {
        /** Activity is about to start — sent to enrolled residents and staff. */
        ACTIVITY_REMINDER,

        /** Activity was cancelled or rescheduled — sent to enrolled residents, staff, and family. */
        ACTIVITY_CANCELLED,

        /** Resident was enrolled in an activity — sent to the resident and family members. */
        ENROLLMENT_CONFIRMED,

        /**
         * Resident actually attended an activity (attendance logged as ATTENDED).
         * Primarily family-facing: lets relatives know their loved one participated.
         */
        ATTENDANCE_LOGGED,

        /**
         * A new photo from an activity the resident attended has been posted.
         * Family-facing hook for Epic 6 (Photo Sharing) — infrastructure ready now,
         * trigger wired when photo upload is implemented.
         */
        PHOTO_AVAILABLE,

        /**
         * Resident's participation rate has dropped below the configured threshold.
         * Sent to family members and directors to prompt follow-up.
         */
        LOW_PARTICIPATION_ALERT,

        /** Manual broadcast from a Director to all residents or a targeted group. */
        BROADCAST
    }
}
