package com.lifeenrichment.entity;

import com.lifeenrichment.entity.NotificationPreference.NotificationType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Immutable audit record of every notification dispatch attempt.
 *
 * <p>A row is written before the channel adapter is called; the status is updated to
 * {@code SENT} or {@code FAILED} after the adapter returns. {@code attemptCount} is
 * incremented on each retry. Permanently failed records (attemptCount ≥ MAX_RETRY_ATTEMPTS)
 * have status {@code FAILED} and a non-null {@code errorMessage}.
 *
 * <p>Four database indexes support the most common access patterns:
 * <ul>
 *   <li>{@code idx_notif_log_user} — history queries for a specific recipient</li>
 *   <li>{@code idx_notif_log_status} — retry scheduler polling for {@code RETRYING} rows</li>
 *   <li>{@code idx_notif_log_reference} — correlation queries by activity / enrollment ID</li>
 *   <li>{@code idx_notif_log_sent_at} — time-range queries and dashboard reporting</li>
 * </ul>
 *
 * <p>Records are append-only by convention; no log row should ever be deleted or have its
 * core fields mutated after creation. Only {@code status}, {@code errorMessage}, and
 * {@code attemptCount} are updated in-place by the retry mechanism.
 *
 * @see NotificationPreference
 * @see NotificationType
 */
@Entity
@Table(name = "notification_logs",
       indexes = {
           @Index(name = "idx_notif_log_user",      columnList = "user_id"),
           @Index(name = "idx_notif_log_status",    columnList = "status"),
           @Index(name = "idx_notif_log_reference", columnList = "reference_id"),
           @Index(name = "idx_notif_log_sent_at",   columnList = "sent_at")
       })
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class NotificationLog {

    /** Surrogate primary key; UUID generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The user who was the intended recipient of this notification.
     * Loaded lazily because most log queries only need scalar fields.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The event type that triggered this notification dispatch.
     * Mirrors the same enum used in {@link NotificationPreference} so preference
     * lookups and log queries share a consistent vocabulary.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "notification_type", nullable = false)
    private NotificationType notificationType;

    /**
     * The delivery channel used for this specific dispatch attempt.
     * A single notification event may produce multiple log rows when several
     * channels (e.g. EMAIL + PUSH) are enabled for the user.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Channel channel;

    /**
     * Current delivery outcome for this log entry.
     * Starts as {@code RETRYING} at creation time; updated to {@code SENT} on success
     * or {@code FAILED} once the maximum retry limit is reached.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private DeliveryStatus status = DeliveryStatus.RETRYING;

    /** ID of the related entity (activity, enrollment, etc.) for correlation. */
    @Column(name = "reference_id")
    private UUID referenceId;

    /**
     * Human-readable summary of the notification content that was sent.
     * Stored as TEXT to accommodate long broadcast messages; may be {@code null}
     * for system-generated short notifications.
     */
    @Column(columnDefinition = "TEXT")
    private String message;

    /** Populated on delivery failure; null on success. */
    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    /**
     * Number of dispatch attempts made for this log entry.
     * Starts at {@code 0} and is incremented by the retry scheduler on each
     * failed attempt. When it reaches the configured cap the status is set to
     * {@code FAILED} and no further retries are scheduled.
     */
    @Builder.Default
    @Column(name = "attempt_count", nullable = false)
    private int attemptCount = 0;

    /**
     * Timestamp recorded automatically when this log row is first persisted.
     * Named {@code sent_at} to reflect the moment the first dispatch was attempted,
     * not necessarily the moment delivery was confirmed.
     */
    @CreationTimestamp
    @Column(name = "sent_at", updatable = false)
    private LocalDateTime sentAt;

    /**
     * Delivery channel options for outbound notifications.
     *
     * <p>Each constant maps to a concrete {@code NotificationChannel} implementation:
     * {@code EmailNotificationChannel}, {@code SmsNotificationChannel}, or
     * {@code PushNotificationChannel}.
     */
    public enum Channel {
        /** Outbound email via SMTP / Amazon SES, rendered from a Thymeleaf template. */
        EMAIL,

        /** SMS message sent through the configured SMS gateway (e.g. Twilio). */
        SMS,

        /** Firebase Cloud Messaging push notification to a registered device token. */
        PUSH
    }

    /**
     * Possible outcomes of a notification dispatch attempt.
     */
    public enum DeliveryStatus {
        /** The channel adapter accepted the message without error. */
        SENT,

        /** All retry attempts exhausted; the message was never successfully delivered. */
        FAILED,

        /** At least one attempt was made but delivery is not yet confirmed; eligible for retry. */
        RETRYING
    }
}
